Targpiast/Controllers/OperatorController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web.Mvc;
using Targpiast.Logic.Repositories;
using Targpiast.Models;

namespace Targpiast.Controllers
{
    /* Spis operatorów */
    public class OperatorController : Controller
    {
        private readonly IOperatorsRepository operatorsRepository;
        private readonly IErrorRepository _errorRepository;
        public OperatorController(IOperatorsRepository objIrepository, IErrorRepository errorRepository)
        {
            operatorsRepository = objIrepository;
            _errorRepository = errorRepository;
        }

        public ActionResult Index()
        {
            return View(operatorsRepository.AllLocalizationsWithOperators);
        }

        #region Localization methods

        public ActionResult AddLocalization(string locName)
        {
            operatorsRepository.InsertOrUpdate(new Localization
            {
                LocalizationName = locName
            });

            try
            {
                operatorsRepository.Save();
                return Json(new { OK = true }, JsonRequestBehavior.AllowGet);
            }
            catch (DbEntityValidationException e)
            {
                var messages = new List<string>();
                foreach (var validationErrors in e.EntityValidationErrors)
                {
                    messages.AddRange(validationErrors.ValidationErrors.Select(validationError => Helpers.CodeHelpers.ReplaceToFriendlyNames(validationError.ErrorMessage)));
                }
                return Json(new { OK = false, Errors = messages }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                _errorRepository.InsertOrUpdate(new Error(e));
                var messages = new List<string> { "Coś poszło nie tak spróbuj ponownie" };
                return Json(new { OK = false, Errors = messages }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult _Localization(Localization model)
        {
            return PartialView(model);
        }

        public void DeleteLocalization(int id)
        {
            operatorsRepository.DeleteLocalization(id);
        }

        #endregion
        
        #region Operator Methods

        public ActionResult ModifyOperators(IEnumerable<Localization> model)
        {
            foreach (var localization in model)
            {
                operatorsRepository.InsertOrUpdate(localization);
            }
            

            try
            {
                operatorsRepository.Save();
                return Json(new { OK = true }, JsonRequestBehavior.AllowGet);
            }
            catch (DbEntityValidationException e)
            {
                var messages = new List<string>();
                foreach (var validationErrors in e.EntityValidationErrors)
                {
                    messages.AddRange(validationErrors.ValidationErrors.Select(validationError => Helpers.CodeHelpers.ReplaceToFriendlyNames(validationError.ErrorMessage)));
                }
                return Json(new { OK = false, Errors = messages }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                _errorRepository.InsertOrUpdate(new Error(e));
                var messages = new List<string> { "Coś poszło nie tak spróbuj ponownie" };
                return Json(new { OK = false, Errors = messages }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult NewOperator(int locId)
        {
            ViewBag.LocId = locId;
            return PartialView("EditorTemplates/NewOperator", new Operator());
        }

        public ActionResult AddOperator(Operator model, int locId)
        {
            var loc = operatorsRepository.AllLocalizationsWithOperators.Include(p => p.Operators).First(p => p.LocalizationId == locId);
            loc.Operators.Add(model);
            operatorsRepository.InsertOrUpdate(loc);
           
            try
            {
                operatorsRepository.Save();
                return Json(new { OK = true }, JsonRequestBehavior.AllowGet);
            }
            catch (DbEntityValidationException e)
            {
                var messages = new List<string>();
                foreach (var validationErrors in e.EntityValidationErrors)
                {
                    messages.AddRange(validationErrors.ValidationErrors.Select(validationError => Helpers.CodeHelpers.ReplaceToFriendlyNames(validationError.ErrorMessage)));
                }
                return Json(new { OK = false, Errors = messages }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                _errorRepository.InsertOrUpdate(new Error(e));
                var messages = new List<string> { "Coś poszło nie tak spróbuj ponownie" };
                return Json(new { OK = false, Errors = messages }, JsonRequestBehavior.AllowGet);
            }
        }

        public void DeleteOperator(int id)
        {
            operatorsRepository.Delete(id);
        }

        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
               operatorsRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Targpiast/Views/Operator/EditorTemplates/Localization.cshtml
@model Targpiast.Models.Localization

@Html.HiddenFor(p => p.LocalizationId)
<div id="loc-@Model.LocalizationId">
    <div class="col-sm-12 col-md-4 padding-top10">
        <a type="button" href="#"
           data-toggle="modal"
           data-target="#removeContentOperators"
           data-mode="loc"
           data-id="@Model.LocalizationId"
           class="btn btn-primary remove-table full-td-button">Usuń lokalizację</a>
    </div>
    <div class="col-sm-12 col-md-8 padding-top10">
        @Html.EditorFor(p => p.LocalizationName, new { htmlAttributes = new { @class = "full-td-button form-control" } })
    </div>
    <div class="col-sm-12 col-md-12 padding-top10">
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th><i class="fa fa-building pull-right hidden-xs"></i> Nazwa operatora</th>
                        <th><i class="fa fa-opencart pull-right hidden-xs"></i> Asortyment</th>
                        <th><i class="fa fa-thumb-tack pull-right hidden-xs"></i> Numer stanowiska</th>
                        <th><i class="fa fa-envelope-o pull-right hidden-xs"></i> Dane kontaktowe</th>
                        <th>Akcje</th>
                    </tr>
                </thead>
                <tbody>
                    @Html.Action("NewOperator", "Operator", new { locId = Model.LocalizationId })
                    @Html.EditorFor(x => x.Operators)
                </tbody>
            </table>
        </div>
    </div>
</div>

Targpiast/Views/Operator/EditorTemplates/NewOperator.cshtml
@model Targpiast.Models.Operator

<tr id="new-operator-form-@ViewBag.LocId.ToString()">
    <td class="fullfill">@Html.EditorFor(p => p.OperatorName, new { htmlAttributes = new { @class = "full-td-editor form-control" } })</td>
    <td class="fullfill">@Html.EditorFor(p => p.ProductCategory, new { htmlAttributes = new { @class = "full-td-editor form-control" } })</td>
    <td class="fullfill">@Html.EditorFor(p => p.ObjectNumber, new { htmlAttributes = new { @class = "full-td-editor form-control" } })</td>
    <td class="fullfill">@Html.EditorFor(p => p.ContactData, new { htmlAttributes = new { @class = "full-td-editor form-control" } })</td>
    <td class="fullfill"><a class="btn btn-sm btn-success js-submit-form full-td-button" data-id="@ViewBag.LocId"> Dodaj</a></td>
</tr>

Targpiast/Views/Operator/EditorTemplates/Operator.cshtml
@model Targpiast.Models.Operator

<tr id="oper-@Model.OperatorId">
	@Html.HiddenFor(p => p.OperatorId)
	<td class="fullfill">@Html.EditorFor(p => p.OperatorName, new { htmlAttributes = new { @class = "full-td-editor form-control" } })</td>
	<td class="fullfill">@Html.EditorFor(p => p.ProductCategory, new { htmlAttributes = new { @class = "full-td-editor form-control" } })</td>
	<td class="fullfill">@Html.EditorFor(p => p.ObjectNumber, new { htmlAttributes = new { @class = "full-td-editor form-control" } })</td>
	<td class="fullfill">@Html.EditorFor(p => p.ContactData, new { htmlAttributes = new { @class = "full-td-editor form-control" } })</td>
	<td class="fullfill">
		<a type="button" href="#"
		   data-toggle="modal"
		   data-target="#removeContentOperators"
		   data-mode="oper"
		   data-id="@Model.OperatorId"
		   class="btn btn-primary remove-row full-td-button">Usuń</a>
	</td>
</tr>