Targpiast/Controllers/InfoController.cs
using System.Web.Mvc;

namespace Targpiast.Controllers
{
    /* Informacje praktyczne */
    public class InfoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Rules()
        {
            return View();
        }
        
        public ActionResult Downloads()
        {
            return View();
        }

        public ActionResult MarketPlan()
        {
            return View();
        }

	    public ActionResult Monitoring()
	    {
		    return View();
	    }
	}
}

Targpiast/Views/Shared/_Footer.cshtml
<footer id="footer">
    <div id="footer-inner">
        <div class="container">
            <div class="spaced">
                <div class="row">
                    <div class="col-md-12 hidden-sm hidden-xs">
                        <img alt="[Targpiast Logo]" src="@Url.Content("~/Content/assets/images/tp-footer-logo.png")" class="tp-footer-logo" />
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 col-sm-12">
                        <p>
                            Targpiast Sp. z o.o. <br />
                            ul. Obornicka 235-237<br />
                            51-114 Wrocław<br /><br />
                            <strong>e-mail:</strong> <a href="mailto:sekretariat@targpiast.com.pl" class="footer-link">sekretariat@targpiast.com.pl</a><br />
                            <strong>WWW:</strong> <a href="#" class="footer-link">www.targpiast.com.pl</a><br />
                        </p>
                    </div>

                    <div class="col-md-5 col-sm-12 box-line padding-right-30">
                        <p>
                            <strong>Kapitał zakładowy:</strong> 1 332 500 PLN<br /><br />
                            <strong>NIP:</strong> 895-15-84-803<br />
                            <strong>REGON:</strong> 931136687<br />
                            <strong>KRS:</strong> 000 162 170 Sąd Rejonowy dla Wrocławia Fabrycznej
                            we&nbsp;Wrocławiu VI Wydział Gospodarczy KRS
                        </p>
                    </div>

                    <div class="col-md-3 hidden-sm hidden-xs padding-left-30">
                        <a href="https://pl-pl.facebook.com/Targpiast" class="social fa fa-facebook"></a>
                        <a href="https://www.youtube.com/channel/UCYaS_9YV55cSPKY3veHvcOg" class="social fa fa-youtube"></a>
                        <br /><br />
                        <a href="@Url.Action("Downloads", "Info", new {Area = ""})" class="download">
                            <i class="download-materials-icon"></i>Materiały do pobrania
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <hr />

        <div class="copyright">
            <div class="container text-center">
                Wszelkie prawa zastrzeżone © Targpiast Sp. z o. o. &bull; <a href="@Url.Action("PrivacyPolicy", "Home")">Polityka prywatności</a>
            </div>
        </div>
    </div>
</footer>

Targpiast/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript">
        // ReSharper disable All
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] ||
                function() {
                    (i[r].q = i[r].q || []).push(arguments);
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m);
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-113165125-2', 'auto');
        ga('send', 'pageview');
    </script>

    <meta charset="utf-8" />
    <title>Targpiast - Spiżarnia Wrocławia i Dolnego Śląska | @ViewBag.Title</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <!-- mobile settings -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="@Url.Content("~/Content/assets/favicon_tp.ico")">
    <link rel="icon" type="image/png" href="@Url.Content("~/Content/assets/favicon_tp.png")">

    <!-- WEB FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700,800&amp;subset=latin,latin-ext,cyrillic,cyrillic-ext" rel="stylesheet" type="text/css" />

    <!-- CORE CSS -->
    @Styles.Render("~/Content/core_css")

    <!-- REVOLUTION SLIDER -->
    @Styles.Render("~/Content/revolution_slider")

    <!-- SKY FORMS CSS-->
    @Styles.Render("~/Content/sky_forms")

    <!-- MAGNIFIC POPUP CSS-->
    @Styles.Render("~/Content/magnific_popup")

    <!-- DROPZONE CSS-->
    @Styles.Render("~/Content/dropzone")

    <!-- THEME CSS -->
    @Styles.Render("~/Content/theme_css")
    
    <!-- BUSY-LOAD -->
    @Styles.Render("~/Content/busy-load")

    <!-- JQUERY BUNDLE-->
    @Scripts.Render("~/bundles/core-js-jquery")

    <!-- REVOLUTION SLIDER -->
    @Scripts.Render("~/bundles/revolution-slider")

    <!-- MAGNIFIC POPUP BUNDLE-->
    @Scripts.Render("~/bundles/magnific_popup")

    <!-- DROPZONE BUNDLE-->
    @Scripts.Render("~/bundles/dropzone")
    
    <!-- VALIDATION BUNDLE-->
    @Scripts.Render("~/bundles/jQuerry_validation")
    
    <!-- BUSY-LOAD -->
    @Scripts.Render("~/bundles/busy-load")

    <script src="~/Content/assets/js/scripts.js"></script>
    <script src="~/Scripts/cookie.notice.js"></script>
    <!-- CUSTOM CSS -->
    <link href="@Url.Content("~/Content/tp_style_15062018.css")" rel="stylesheet" type="text/css" />
</head>
<body class="smoothscroll">
    <div id="wrapper">
        <div id="header">
            <!-- class="sticky" for sticky menu -->
            <header id="topBar">
                <div class="container">
                    <div class="pull-right fsize13 margin-top10 hide_mobile">

                        <!-- mail , phone -->
                        <a href="tel:+48-71-712-5900">+48-71-712-5900</a>

                        <div class="block text-right">
                            <!-- social -->
                            <a href="https://pl-pl.facebook.com/Targpiast" class="social fa fa-facebook"></a>
                            <a href="https://www.youtube.com/channel/UCYaS_9YV55cSPKY3veHvcOg" class="social fa fa-youtube"></a>
                        </div><!-- /social -->

                    </div>

                    <!-- Logo -->
                    <a class="logo" href="@Url.Action("Index", "Home", new { Area = "" })">
                        <img src="@Url.Content("~/Content/assets/images/tp_logo.jpg")" />
                        <span class="logo-txt">
                            <span class="bold">Rolno-spożywczy rynek hurtowy</span> we Wrocławiu
                        </span>
                    </a>
                </div><!-- /.container -->
            </header>
        </div>
        
        @if (User.Identity.IsAuthenticated)
        {
            <div class="container">
                <div style="margin-bottom: 40px">
                    <section>
                        <a href="@Url.Action("LogOff", "Account")" type="button" class="btn btn-primary btn-lg btn-block js-add-news">Wyloguj z panelu administratora</a>
                        <a href="@Url.Action("Index", "GoogleAnalytics")" type="button" class="btn btn-success btn-lg btn-block">Statystyki witryny</a>
                    </section>
                </div>
            </div>
        }

        @Html.Partial("_TopNav")

        @RenderBody()

        @Html.Partial("_Footer")

    </div>

    <!-- modal dialog -->
    <div class="modal fade" id="removeContent" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <!-- modal header -->
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Usuń element</h4>
                </div><!-- /modal header -->
                <!-- modal body -->
                <div class="modal-body">
                    Czy na pewno chcesz usunąć ten element ? Zmiany są nieodwracalne!
                </div>
                <!-- /modal body -->

                <div class="modal-footer">
                    <!-- modal footer -->
                    <button class="btn btn-default" data-dismiss="modal">Anuluj</button> <a id="deleteButton" type="button" href="#" class="btn btn-primary">Usuń</a>
                </div><!-- /modal footer -->
            </div>
        </div>
    </div>

</body>
</html>

<script>
    $(document).ready(function() {
        $('.js-remove-content').click(function() {
            $("#deleteButton").attr("href", $(this).attr("data-href"));
        });

        $.busyLoadSetup({ animation: "slide", background: "rgba(150, 150, 150, 0.90)", spinner: "accordion" });
    });
</script>

Targpiast/Views/Shared/_TopNav.cshtml
<header id="topNav">
    <div class="container">

        <!-- Mobile Menu Button -->
        <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Top Nav -->
        <div class="navbar-collapse nav-main-collapse collapse">
            <nav class="nav-main">
                <ul id="topMain" class="nav nav-pills nav-main">
                    <li class="@Html.IsSelected("Home", "Index")">
                        <a href="@Url.Action("Index", "Home", new { Area = "" })">
                            Start
                        </a>
                    </li>
                    <li class="@Html.IsSelected("About", "Index") @Html.IsSelected("About", "History") @Html.IsSelected("About", "RegisterData")">
                        <a class="dropdown-toggle" href="#">
                            O firmie <span class="fa fa-caret-down"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "About", new {Area = ""})"> Struktura i profil spółki</a></li>
                            <li><a href="@Url.Action("History", "About", new {Area = ""})"> Historia</a></li>
                            <li><a href="@Url.Action("RegisterData", "About", new {Area = ""})"> Dane rejestrowe</a></li>
                        </ul>
                    </li>
                    <li class="@Html.IsSelected("Price", "Index")">
                        <a href="@Url.Action("Index", "Price", new { Area = "" })">
                            Notowania cenowe
                        </a>
                    </li>
                    <li class="@Html.IsSelected("News", "Index") @Html.IsSelected("News", "News")">
                        <a href="@Url.Action("Index", "News", new { Area = "" })">
                            Wydarzenia
                        </a>
                    </li>
                    <li class="@Html.IsSelected("Info", "Index") @Html.IsSelected("Info", "Rules") @Html.IsSelected("Info", "Downloads") @Html.IsSelected("Info", "MarketPlan")">
                        <a class="dropdown-toggle" href="#">
                            Informacje praktyczne <span class="fa fa-caret-down"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("MarketPlan", "Info", new {Area = ""})"> Plan rynku</a></li>
                            <li><a href="@Url.Action("Index", "Info", new {Area = ""})"> Opłaty</a></li>
                            <li><a href="@Url.Action("Rules", "Info", new {Area = ""})"> Regulamin</a></li>
                            <li><a href="@Url.Action("Downloads", "Info", new {Area = ""})"> Do pobrania</a></li>
	                        <li><a href="@Url.Action("Monitoring", "Info", new {Area = ""})"> Monitoring wizyjny</a></li>
                        </ul>
                    </li>
                    <li class="@Html.IsSelected("Gallery", "Index") @Html.IsSelected("Gallery", "Video") ">
                        <a class="dropdown-toggle" href="#">
                            Galeria <span class="fa fa-caret-down"></span>
                        </a>

                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Gallery", new {Area = ""})"> Foto</a></li>
                            <li><a href="@Url.Action("Video", "Gallery", new {Area = ""})"> Wideo</a></li>
                        </ul>
                    </li>
                    <li class="@Html.IsSelected("Operator", "Index")">
                        <a href="@Url.Action("Index", "Operator", new { Area = "" })">
                            Spis operatorów
                        </a>
                    </li>
                    <li class="@Html.IsSelected("Eco", "Index") @Html.IsSelected("Eco", "News") @Html.IsSelected("Eco", "Operators") @Html.IsSelected("Eco", "SingleNews")">
                        <a class="dropdown-toggle" href="#">
                            Eco Targpiast <span class="fa fa-caret-down"></span>
                        </a>
                        
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Eco", new {Area = ""})"> Wizja projektu</a></li>
                            <li><a href="@Url.Action("News", "Eco", new {Area = ""})"> Wydarzenia</a></li>
                            <li><a href="@Url.Action("Operators", "Eco", new {Area = ""})"> Eko dostawcy</a></li>
                        </ul>
                    </li>
                    <li class="@Html.IsSelected("Contact", "Index")">
                        <a class="dropdown-toggle" href="#">
                            Kontakt <span class="fa fa-caret-down"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Contact", new {Area = ""})"> Dane kontaktowe</a></li>
                            <li><a href="@Url.Action("Map", "Contact", new {Area = ""})"> Mapa dojazdowa</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
        <!-- /Top Nav -->
    </div><!-- /.container -->
</header>