Targpiast/Controllers/PriceController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Targpiast.Logic.Repositories;
using Targpiast.Models;
using Spire.Pdf;
using Spire.Pdf.Graphics;
using Spire.Pdf.Tables;

namespace Targpiast.Controllers
{
    /* Notowania cenowe */
    public class PriceController : Controller
    {
        private readonly IPriceListsRepository _priceListsRepository;
        private readonly IErrorRepository _errorRepository;

        public PriceController(IPriceListsRepository priceListsIrepository, IErrorRepository errorRepository)
        {
            _priceListsRepository = priceListsIrepository;
            _errorRepository = errorRepository;
        }

        [HttpGet]
        public ActionResult Index()
        {
            if (TempData["PriceListId"] != null)
            {
                var id = (int) TempData["PriceListId"];
                TempData["PriceListId"] = null;
                var allPriceLists = _priceListsRepository.AllPriceLists.OrderByDescending(p => p.PriceListDateTime);
                ViewBag.PriceListToShow = _priceListsRepository.FindPriceList(id);
                return View(allPriceLists);
            }
            else
            {
                var allPriceLists = _priceListsRepository.AllPriceLists.OrderByDescending(p => p.PriceListDateTime);
                ViewBag.PriceListToShow = _priceListsRepository.FindPriceList(allPriceLists.First().PriceListId);
                return View(allPriceLists);
            }
        }

        [HttpPost]
        public ActionResult Index(int id)
        {
            TempData["PriceListId"] = id;
            return JavaScript("location.reload(true)");
        }

        public ActionResult _PriceList(PriceList model)
        {
            return PartialView(model);
        }

        public ActionResult PriceListEditor(PriceList model)
        {
            ViewBag.PriceListId = model.PriceListId;
            return PartialView("_PriceListEditor", model.Products.OrderBy(p => p.ProductName));
        }

        public JsonResult CopyPriceList(IEnumerable<Product> model)
        {
            try
            {
                _priceListsRepository.CopyPriceList(model);
                return Json(new {OK = true}, JsonRequestBehavior.AllowGet);
            }
            catch (DbEntityValidationException e)
            {
                var messages = new List<string>();
                foreach (var validationErrors in e.EntityValidationErrors)
                {
                    messages.AddRange(validationErrors.ValidationErrors.Select(validationError => Helpers.CodeHelpers.ReplaceToFriendlyNames(validationError.ErrorMessage)));
                }
                return Json(new { OK = false, Errors = messages }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                _errorRepository.InsertOrUpdate(new Error(e));
                var messages = new List<string> {"Coś poszło nie tak spróbuj ponownie"};
                return Json(new { OK = false, Errors = messages }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult SavePriceList(IEnumerable<Product> model)
        {
            foreach (var product in model)
            {
                _priceListsRepository.InsertOrUpdate(product);
            }
            
            try
            {
                _priceListsRepository.Save();
                return Json(new { OK = true }, JsonRequestBehavior.AllowGet);
            }
            catch (DbEntityValidationException e)
            {
                var messages = new List<string>();
                foreach (var validationErrors in e.EntityValidationErrors)
                {
                    messages.AddRange(validationErrors.ValidationErrors.Select(validationError => Helpers.CodeHelpers.ReplaceToFriendlyNames(validationError.ErrorMessage)));
                }
                return Json(new { OK = false, Errors = messages }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                _errorRepository.InsertOrUpdate(new Error(e));
                var messages = new List<string> { "Coś poszło nie tak spróbuj ponownie" };
                return Json(new { OK = false, Errors = messages }, JsonRequestBehavior.AllowGet);
            }
        }

        public void DeletePriceList(int id)
        {
            _priceListsRepository.DeletePriceList(id);
        }

        public void DeleteProduct(int id)
        {
            _priceListsRepository.Delete(id);
        }

        public ActionResult NewProduct(int priceListId)
        {
            ViewBag.PriceListId = priceListId;
            return PartialView("EditorTemplates/NewProduct", new Product());
        }

        public JsonResult AddProduct(Product model, int plId)
        {
            var priceList = _priceListsRepository.AllPriceLists.First(p => p.PriceListId == plId);
            priceList.Products.Add(model);
            _priceListsRepository.InsertOrUpdate(priceList);

            try
            {
                _priceListsRepository.Save();
                return Json(new { OK = true, ID = plId }, JsonRequestBehavior.AllowGet);
            }
            catch (DbEntityValidationException e)
            {
                var messages = new List<string>();
                foreach (var validationErrors in e.EntityValidationErrors)
                {
                    messages.AddRange(validationErrors.ValidationErrors.Select(validationError => Helpers.CodeHelpers.ReplaceToFriendlyNames(validationError.ErrorMessage)));
                }
                return Json(new { OK = false, Errors = messages }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                _errorRepository.InsertOrUpdate(new Error(e));
                var messages = new List<string> { "Coś poszło nie tak spróbuj ponownie" };
                return Json(new { OK = false, Errors = messages }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult GeneratePdf(PriceList model)
        {
            //Create a pdf document.
            var doc = new PdfDocument();
            var sec = doc.Sections.Add();
            sec.PageSettings.Width = PdfPageSize.A4.Width;
            PdfPageBase page = sec.Pages.Add();
            float y = 10;

            //Title
            var brush1 = PdfBrushes.Black;
            var font1 = new PdfTrueTypeFont(new Font("Arial", 16f, FontStyle.Bold), true);
            var format1 = new PdfStringFormat(PdfTextAlignment.Center);
            var font2 = new PdfTrueTypeFont(new Font("Arial", 10f, FontStyle.Regular), true);
            page.Canvas.DrawString($"Notowania cenowe: {model.PriceListDateTime.ToShortDateString()}", font1, brush1, page.Canvas.ClientSize.Width / 2, y, format1);
            
            y = y + font1.MeasureString($"Notowania cenowe: {model.PriceListDateTime.ToShortDateString()}", format1).Height;
            y = y + 5;

            page.Canvas.DrawString("Prezentowane ceny nie stanowią oferty w rozumieniu kodeksu cywilnego.", font2, brush1, page.Canvas.ClientSize.Width / 2, y, format1);

            y = y + font2.MeasureString("Prezentowane ceny nie stanowią oferty w rozumieniu kodeksu cywilnego.", format1).Height;
            y = y + 5;

            var col = new List<string> {"Nazwa produktu;Cena;Jednostka"};
            col.AddRange(_priceListsRepository.AllPriceListsWithProducts.First(p => p.PriceListId == model.PriceListId).Products.Select(p => $"{p.ProductName};{p.Price};{p.Unit}").ToArray());
            var data = col.ToArray();

            var dataSource
                = new string[data.Length][];
            for (var i = 0; i < data.Length; i++)
            {
                dataSource[i] = data[i].Split(';');
            }


            var table = new PdfTable
            {
                Style =
                {
                    CellPadding = 2,
                    BorderPen = new PdfPen(brush1, 0.75f),
                    HeaderStyle = {StringFormat = new PdfStringFormat(PdfTextAlignment.Center)},
                    HeaderSource = PdfHeaderSource.Rows,
                    HeaderRowCount = 1,
                    ShowHeader = true,
                    DefaultStyle = new PdfCellStyle
                    {
                        Font = new PdfTrueTypeFont(new Font("Arial", 10f),true)
                    }
                }
            };
            table.Style.HeaderStyle.BackgroundBrush = PdfBrushes.LightGray;
            table.DataSource = dataSource;
            foreach (PdfColumn column in table.Columns)
            {
                column.StringFormat = new PdfStringFormat(PdfTextAlignment.Center, PdfVerticalAlignment.Middle);
            }

            table.Draw(page, new PointF(0, y));

            var stream = new MemoryStream();
            doc.SaveToStream(stream);
            doc.Close();
            stream.Position = 0;

            var result = new FileStreamResult(stream, "application/pdf");
            return result;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _priceListsRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Targpiast/Views/Price/Index.cshtml
@using Targpiast.Models
@model IEnumerable<PriceList>

@{
    ViewBag.Title = "Notowania cenowe";
    var selId = ((PriceList)ViewBag.PriceListToShow).PriceListId;
}

<section class="std-page-header bg2"></section>

<section id="price-list">
    <div id="editArea" class="container">
        <h2>
            Notowania cenowe
        </h2>


        <div class="col-sm-12 col-md-4 padding-top10">
            @Html.ActionLink("Drukuj cennik", "GeneratePdf", (PriceList)ViewBag.PriceListToShow, new { target = "_blank", type = "button", @class = "btn btn-primary  full-td-button" })
        </div>
        <div class="col-sm-12 col-md-4 padding-top10">
            <h4 class="before-dropdown pull-right" style="margin-top: 4px">Pozycje archiwalne:</h4>
        </div>
        <div class="col-sm-12 col-md-4 padding-top10">
            @Html.DropDownList("priceListDropDownList", new SelectList(Model, "PriceListId", "PriceListDateTime"), new { @class = "select  full-td-button" })
        </div>
        <div class="col-sm-12 col-md-12 padding-top10">
            <div class="divider half-margins"></div>
        </div>
        <div class="col-sm-12 col-md-4 padding-top10">
            @if (User.Identity.IsAuthenticated)
            {
                <a type="button" href="#"
                   data-toggle="modal"
                   data-target="#removeContentPriceList"
                   data-id="@(((PriceList) ViewBag.PriceListToShow).PriceListId)"
                   class="btn btn-primary remove-table full-td-button"><i class="icon-trash icon-large"></i>Usuń cennik</a>
            }
        </div>
        <div class="col-sm-12 col-md-4 padding-top10">
            @if (User.Identity.IsAuthenticated)
            {
                <button type="button" class="btn btn-success js-copy-form full-td-button"> Utwórz nowy cennik</button>
            }
        </div>
        <div class="col-sm-12 col-md-4 padding-top10">
            @if (User.Identity.IsAuthenticated)
            {
                <button type="button" class="btn btn-success js-submit-form full-td-button"> Zmodyfikuj cennik</button>
            }
        </div>
        <div class="col-sm-12 col-md-12 padding-top10">
            @if (User.Identity.IsAuthenticated)
            {
                <div class="divider half-margins"></div>
            }
        </div>
        <div id="ErrorMessage" class="col-md-12  padding-top10"></div>
    </div>
    @(User.Identity.IsAuthenticated ? Html.Action("PriceListEditor", "Price", new { model = (PriceList)ViewBag.PriceListToShow }) : Html.Partial("_PriceList", (PriceList)ViewBag.PriceListToShow))
</section>

<!-- modal dialog for PriceList -->
<div class="modal fade" id="removeContentPriceList" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <!-- modal header -->
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Usuń element</h4>
            </div><!-- /modal header -->
            <!-- modal body -->
            <div class="modal-body">
                Czy na pewno chcesz usunąć ten element ? Zmiany są nieodwracalne!
            </div>
            <!-- /modal body -->

            <div class="modal-footer">
                <!-- modal footer -->
                <button class="btn btn-default" data-dismiss="modal">Anuluj</button> <a id="deleteButtonPriceList" data-dismiss="modal" data-id="" data-mode="" type="button" href="#" class="btn btn-primary">Usuń</a>
            </div><!-- /modal footer -->
        </div>
    </div>
</div>

<script>
    var DIV_START =
        "<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button>";
    var DIV_END =
        "</div>";

    $(document).ready(function () {
        var selectedId = '@selId';
        $("#priceListDropDownList").val(selectedId);
    });

    $("#priceListDropDownList").change(function () {
        $.ajax({
            type: "POST",
            url: '@Url.Action("Index","Price")',
            data: {
                id: $(this).val()
            }
        });
    });

    $("#price-list").on("click", ".remove-row", function () {
        var $this = $(this),
            id = $this.attr("data-id");

        $("#deleteButtonPriceList").attr("data-id", id);
        $("#deleteButtonPriceList").attr("data-mode", 'product');
    });

    $("#price-list").on("click", ".remove-table", function () {
        var $this = $(this),
            id = $this.attr("data-id");

        $("#deleteButtonPriceList").attr("data-id", id);
        $("#deleteButtonPriceList").attr("data-mode", 'priceList');
    });


    $("#deleteButtonPriceList").on("click",
        function () {
            ClearValidation();
            var $this = $(this),
                id = $this.attr("data-id"),
                mode = $this.attr("data-mode");

            if (mode === 'product') {
                $.ajax({
                    url: '@Url.Action("DeleteProduct", "Price")',
                    data: {
                        id: id
                    },
                    success: $('#' + id).remove()
                });
            } else {
                $.ajax({
                    url: '@Url.Action("DeletePriceList", "Price")',
                    before: $("#editArea").busyLoad("show"),
                    data: {
                        id: id
                    },
                    success: function () {
                        $("#editArea").busyLoad("hide");
                        location.href = '@Url.Action("Index", "Price")';
                    }
                });
            }
        });


    $(".js-copy-form").on("click",
        function(e) {
            e.preventDefault();
            ClearValidation();
            var $form = $("#priceListForm"),
                url = '@Url.Action("CopyPriceList", "Price")';

            $.ajax({
                url: url,
                type: "POST",
                cache: false,
                data: $form.serialize(),
                before: $("#editArea").busyLoad("show"),
                success: function(result) {
                    if (result.OK) {
                        location.href = '@Url.Action("Index", "Price")';
                    } else {
                        if (result.Errors != undefined) {

                            var errorModalHtml = DIV_START;
                            $.each(result.Errors,
                                function(index, value) {
                                    errorModalHtml += value;
                                    errorModalHtml += "<br />";
                                });
                            errorModalHtml += DIV_END;

                            ColorValidationErrors();
                            $("#ErrorMessage").append(errorModalHtml);
                        }
                    }
                    $("#editArea").busyLoad("hide");
                }
            });
        });

    $(".js-submit-form").on("click", function (e) {
        e.preventDefault();
        ClearValidation();
        var $form = $("#priceListForm"),
            url = '@Url.Action("SavePriceList", "Price")',
            id = $(this).attr("data-id");

        $.ajax({
            url: url,
            type: "POST",
            cache: false,
            data: $form.serialize(),
            before: $("#editArea").busyLoad("show"),
            success: function (result) {
                if (result.OK) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Index","Price")',
                        data: {
                            id: id
                        }
                    });
                } else {
                    if (result.Errors != undefined) {

                        var errorModalHtml = DIV_START;
                        $.each(result.Errors, function (index, value) {
                            errorModalHtml += value;
                            errorModalHtml += "<br />";
                        });
                        errorModalHtml += DIV_END;

                        ColorValidationErrors();
                        $("#ErrorMessage").append(errorModalHtml);
                    }
                }
                $("#editArea").busyLoad("hide");
            }
        });
    });

    $(".js-add-row").on("click", function (e) {
        e.preventDefault();
        ClearValidation();
        var $form = $("#newProductForm"),
            url = $form.attr('action');

        $.ajax({
            url: url,
            type: "POST",
            cache: false,
            data: $form.serialize(),
            success: function (result) {
                if (result.OK) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Index","Price")',
                        data: {
                            id: result.ID
                        }
                    });
                } else {
                    if (result.Errors != undefined) {

                        var errorModalHtml = DIV_START;
                        $.each(result.Errors,
                            function(index, value) {
                                errorModalHtml += value;
                                errorModalHtml += "<br />";
                            });
                        errorModalHtml += DIV_END;

                        ColorValidationErrorsSingle();
                        $("#ErrorMessage").append(errorModalHtml);
                    }
                }
            }
        });
    });

    function ColorValidationErrorsSingle() {

        $("input[name='ProductName']").each(function() {
            var $this = $(this);
            if (this.value === undefined || this.value === "" || this.value.length > 50) {
                $this.addClass("bg-input-validation");
            } else {
                $this.removeClass("bg-input-validation");
            }
        });

        $("input[name='Price']").each(function() {
            var $this = $(this);
            if (this.value === undefined || this.value === "" || this.value.length > 20) {
                $this.addClass("bg-input-validation");
            } else {
                $this.removeClass("bg-input-validation");
            }
        });

        $("input[name='Unit']").each(function() {
            var $this = $(this);
            if (this.value === undefined || this.value === "" || this.value.length > 10) {
                $this.addClass("bg-input-validation");
            } else {
                $this.removeClass("bg-input-validation");
            }
        });
    }

    function ColorValidationErrors() {

        $("input[name$='.ProductName']").each(function() {
            var $this = $(this);
            if (this.value === undefined || this.value === "" || this.value.length > 50) {
                $this.addClass("bg-input-validation");
            } else {
                $this.removeClass("bg-input-validation");
            }
        });

        $("input[name$='.Price']").each(function() {
            var $this = $(this);
            if (this.value === undefined || this.value === "" || this.value.length > 20) {
                $this.addClass("bg-input-validation");
            } else {
                $this.removeClass("bg-input-validation");
            }
        });

        $("input[name$='.Unit']").each(function() {
            var $this = $(this);
            if (this.value === undefined || this.value === "" || this.value.length > 10) {
                $this.addClass("bg-input-validation");
            } else {
                $this.removeClass("bg-input-validation");
            }
        });
    }

    function ClearValidation() {
        $("#ErrorMessage").empty();
        $(".bg-input-validation").each(function() {
            $(this).removeClass("bg-input-validation");
        });
    }
</script>

Targpiast/Views/Price/_PriceList.cshtml
@model Targpiast.Models.PriceList

<div class="container">
    <h4>@Model.PriceListDateTime.ToShortDateString()</h4>
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th><i class="fa fa-list pull-right hidden-xs"></i> Nazwa produktu</th>
                <th><i class="fa fa-money pull-right hidden-xs"></i> Cena</th>
                <th><i class="fa fa-database pull-right hidden-xs"></i> Jednostka</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var product in Model.Products.OrderBy(p => p.ProductName))
            {
                <tr>
                    <td>@product.ProductName</td>
                    <td>@product.Price</td>
                    <td>@product.Unit</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

Targpiast/Views/Price/_PriceListEditor.cshtml
@using Targpiast.Models
@model IEnumerable<Product>

<div class="container">

    <div class="table-responsive">
        <table id="tablePriceList" class="table table-bordered table-striped">
            <thead>
            <tr>
                <th><i class="fa fa-list pull-right hidden-xs"></i> Nazwa produktu</th>
                <th><i class="fa fa-money pull-right hidden-xs"></i> Cena</th>
                <th><i class="fa fa-database pull-right hidden-xs"></i> Jednostka</th>
                <th><i class=""></i> Akcja</th>
            </tr>
            </thead>
            <tbody>
            @Html.Action("NewProduct", "Price", new { priceListId = ViewBag.PriceListId })
            @using (Html.BeginForm(null, null, FormMethod.Post, new {id = "priceListForm"}))
            {
                @Html.EditorForModel()
            }
            </tbody>
        </table>
    </div>
</div>